---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
  labels:
    app: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
      - name: task-manager
        env:
          - name: MINIO_URL
            value: minio:9000
        image: task_manager
        # should be kustomized to dev only
        command:
          - "bash"
          - "-c" 
          - "python -m debugpy --listen 5678 -m uvicorn --host 0.0.0.0 task_manager.server:app --reload"
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager
spec:
  selector:
    app: task-manager
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---